### ISSUE TITLE
Challenge failing - domain routing

### ISSUE THREAD

**Issue by dmarcos89** [Daanra/laravel-lets-encrypt#2]
Hey there, first of all, thanks for the amazing package.

Im trying to use it for creating ssl certs for clients of my saas app. 

Basically after users register in the app, they get a custom subdomain, in the form: client1.myapp.com, client2.myapp.com.., etc. And they can use a CNAME to use a custom domain they bring, classic SAAS.

I configured a CNAME record which is reaching the app fine, but in this case when creating a certificate I am failing on the challenge step, not being able to validate the file in `.well_known...`.

My routes file looks like this:
```
Route::group(['domain' => '{company:slug}.'.config('app.domain')], function () {
	Route::group(['middleware' => 'tenant'], function(){
		Route::get('', [HomeController::class, 'index']);

...
...
```

I'm using the config file as is, only updating the api_url to use the production one.

Checking in the server, i can't see any file created in `public/.well_known...`. Should I be able to see the file even if challenge fails? Maybe that's where i'm having the issue so the file is never uploaded...

Thanks in advance for any help!

**Comment by Daanra** [comment]
Hey,

The documentation is a bit vague on this but, by default, the challenge is stored in `public/.well-known/acme-challenge/` on your default filesystem. So if you use the standard filesystem settings this will be your local filesystem under the path `storage/app/public/.well-known/acme-challenge/`. If the challenge fails after creating the challenge then the file should still be visible in this directory. 

If needed, you can change the filesystem and the path used in the config file.

To serve the challenge to LetsEncrypt, you could add a controller that returns this file on the endpoint `/.well-known/acme-challenge`

So something along the lines of:
```php
 Route::get('/.well-known/acme-challenge/{token}', function ($company, string $token) {
     return Storage::disk('public')->get('.well-known/acme-challenge/' . $token);
 })
 ```

Alternatively, you could update your NGINX or Apache configuration to return this file.

I'll update the documentation shortly to be a bit more clear on that.

Let me know if this solves your problem 😃

**Comment by dmarcos89** [comment]
@Daanra Many thanks for helping out. I am getting closer now, I had to adjust my routes file based on your comment and update my Nginx config in forge to allow .well-known .... 

so now I can see the file uploaded, here's an example: `https://test.tonirpropiedades.com/.well-known/acme-challenge/5x4STxw6avdtycBssj_MPUbS843MZejjinxqIg6vJ0M`

But for some reason the challenge is still failing..
For creating the certificate im testing it with:
```
Route::get('/certificate/{domain}', function($domain) {
	\Daanra\LaravelLetsEncrypt\Facades\LetsEncrypt::createNow($domain);
	echo $domain;
});
```

And when testing for my domain `test.tonirpropiedades.com`

```
AcmePhp\Core\Exception\Protocol\ChallengeFailedException
Challenge failed (response: {"type":"http-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:unauthorized","detail":"Invalid response from https:\/\/test.tonirpropiedades.com\/.well-known\/acme-challenge\/5x4STxw6avdtycBssj_MPUbS843MZejjinxqIg6vJ0M [192.241.147.74]: \"5x4STxw6avdtycBssj_MPUbS843MZejjinxqIg6vJ0M.j69RWXJvfNJ5wWOhbP4Vt5l_g8-VUcJB1ZsJgg07qeg<link rel='stylesheet' type='text\/css' pr\"","status":403},"url":"https:\/\/acme-v02.api.letsencrypt.org\/acme\/chall-v3\/13283102254\/8d0Gdw","token":"5x4STxw6avdtycBssj_MPUbS843MZejjinxqIg6vJ0M","validationRecord":[{"url":"http:\/\/test.tonirpropiedades.com\/.well-known\/acme-challenge\/5x4STxw6avdtycBssj_MPUbS843MZejjinxqIg6vJ0M","hostname":"test.tonirpropiedades.com","port":"80","addressesResolved":["192.241.147.74"],"addressUsed":"192.241.147.74"},{"url":"https:\/\/test.tonirpropiedades.com\/.well-known\/acme-challenge\/5x4STxw6avdtycBssj_MPUbS843MZejjinxqIg6vJ0M","hostname":"test.tonirpropiedades.com","port":"443","addressesResolved":["192.241.147.74"],"addressUsed":"192.241.147.74"}],"validated":"2021-05-20T10:36:04Z"}).
```



Not sure if it helps, but when trying curl in console, getting the following:
```
curl http://test.tonirpropiedades.com/.well-known/acme-challenge/5x4STxw6avdtycBssj_MPUbS843MZejjinxqIg6vJ0M
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
```

I sense there must be some Nginx config causing this...
Again, many thanks for the help.

Damian

**Comment by Daanra** [comment]
@dmarcos89 

It's the debugbar extension that's causing the error. It's manipulating the response before it's sent to LetsEncrypt which causes it to fail.

If you try the following command:
```
curl -k https://test.tonirpropiedades.com/.well-known/acme-challenge/5x4STxw6avdtycBssj_MPUbS843MZejjinxqIg6vJ0M
```

You will see that the debugbar is inserting a bunch of JavaScript and CSS. If you disable the Laravel debug bar (for that endpoint at least) then it should be working.

**Comment by dmarcos89** [comment]
I tried disabling debugbar but still not working unfortunately 😢 

Running the curl call works as expected now. 

Can you imagine anything else that could make this to fail?
This is my Nginx config in Forge, in case you notice anything problematic.
```
# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/ninjaprop.com/before/*;

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name .ninjaprop.com tonirpropiedades.com test.tonirpropiedades.com;
    server_tokens off;
    root /home/forge/ninjaprop.com/public;

    # FORGE SSL (DO NOT REMOVE!)
    ssl_certificate /etc/nginx/ssl/ninjaprop.com/1024264/server.crt;
    ssl_certificate_key /etc/nginx/ssl/ninjaprop.com/1024264/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS_AES_256_GCM_SHA384:TLS-AES-256-GCM-SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS-CHACHA20-POLY1305-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparams.pem;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    # FORGE CONFIG (DO NOT REMOVE!)
    include forge-conf/ninjaprop.com/server/*;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/ninjaprop.com-error.log error;

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        allow all;
    }
}

# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/ninjaprop.com/after/*;


```

Will continue testing, thanks again for taking the time, appreciate it!

**Comment by Daanra** [comment]
Hmm, I'm not sure then.

What's the response in the `ChallengeFailedException`? The exception that is thrown when generating the certificate should indicate what went wrong.

**Comment by dmarcos89** [comment]
This is the exception:

```
Challenge failed (response: {"type":"http-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:unauthorized","detail":"Invalid response from https:\/\/test.tonirpropiedades.com\/.well-known\/acme-challenge\/XwhbBQ8GtgJzi-s0hXBBOUuxrROyGg1pLyve-YN1YPk [192.241.147.74]: 404","status":403},"url":"https:\/\/acme-staging-v02.api.letsencrypt.org\/acme\/chall-v3\/51845215\/6nJYWQ","token":"XwhbBQ8GtgJzi-s0hXBBOUuxrROyGg1pLyve-YN1YPk","validationRecord":[{"url":"http:\/\/test.tonirpropiedades.com\/.well-known\/acme-challenge\/XwhbBQ8GtgJzi-s0hXBBOUuxrROyGg1pLyve-YN1YPk","hostname":"test.tonirpropiedades.com","port":"80","addressesResolved":["192.241.147.74"],"addressUsed":"192.241.147.74"},{"url":"https:\/\/test.tonirpropiedades.com\/.well-known\/acme-challenge\/XwhbBQ8GtgJzi-s0hXBBOUuxrROyGg1pLyve-YN1YPk","hostname":"test.tonirpropiedades.com","port":"443","addressesResolved":["192.241.147.74"],"addressUsed":"192.241.147.74"}],"validated":"2021-05-20T11:37:12Z"}).

```

**Comment by Daanra** [comment]
@dmarcos89 
Weirdly enough, the last exception states that the LetsEncrypt server is receiving a 404 error when trying to access the URL. Before it was able to access it properly and it did find the correct challenge (only the debug bar was adding some extra data).


It could be that this NGINX rule is interfering:
```
location ~ /\.(?!well-known).* {
        allow all;
}
```

I'm not too familiar with NGINX syntax but perhaps you could change it to something like this:
```
location ~ /\..* {
        allow all;
}
```
such that the `.well-known` directory is also allowed

**Comment by dmarcos89** [comment]
Hey mate, I ended up creating certificates manually. 
Will get back to this in the future, thanks for all the help
